version: "3"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - ".env"

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: myproject
      POSTGRES_USER: myprojectuser
      POSTGRES_PASSWORD: myprojectpassword
    volumes:
      - pgdata:/var/lib/postgresql/data 
  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - .:/app
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - django

volumes:
  pgdata: